state_code = [
	{'ap' : 'Andhra Pradesh'},
	{'an' : 'Andaman and Nicobar Islands'},
	{'ar' : 'Arunachal Pradesh'},
	{'as' : 'Assam'},
	{'br' : 'Bihar'},
	{'cg' : 'Chhattisgarh'},
	{'ch' : 'Chandigarh'},
	{'dl' : 'Delhi'},
	{'dd' : 'Daman and Diu'},
	{'dn' : 'Dadra and Nagar Haveli'},
	{'ga' : 'Goa'},
	{'gj' : 'Gujarat'},
	{'hr' : 'Haryana'},
	{'hp' : 'Himachal Pradesh'},
	{'jk' : 'Jammu & Kashmir'},
	{'jh' : 'Jharkhand'},
	{'ka' : 'Karnataka'},
	{'kl' : 'Kerala'},
	{'mp' : 'Madhya Pradesh'},
	{'mh' : 'Maharashtra'},
	{'mn' : 'Manipur'},
	{'ml' : 'Meghalaya'},
	{'mz' : 'Mizoram'},
	{'nl' : 'Nagaland'},
	{'or' : 'Orissa'},
	{'pb' : 'Punjab'},
	{'py' : 'Pondicherry'},
	{'rj' : 'Rajasthan'},
	{'sk' : 'Sikkim'},
	{'tn' : 'Tamil Nadu'},
	{'tr' : 'Tripura'},
	{'ts' : 'Telangana'},
	{'up' : 'Uttar Pradesh'},
	{'uk' : 'Uttarakhand'},
	{'wb' : 'West Bengal'}
]