# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170617_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fuelcompany',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='dailyrate',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='mainapp.FuelCompany'),
        ),
        migrations.RemoveField(
            model_name='dailyrate',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='dailyrate',
            unique_together=set([('fuel', 'city', 'provider')]),
        ),
    ]
